### ISSUE TITLE
Mouse not visible on host, not moving in guest. Keyboard works. (LG: c7666b31) Linux client crashes on copy

### ISSUE THREAD

**Issue by TerminatorNL** [gnif/LookingGlass#135]
Host CPU: `AMD Ryzen 7 1800X Eight-Core Processor`
Host GPU: `NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1)`
Guest GPU: `NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1)`
Host Kernel version: `4.20.4-200.fc29.x86_64`
Host QEMU version: `2:3.0.0-3.fc29`

Note: This is using looking glass compiled at commit c7666b314bde2622328b5ddd7f16c7493c552d01

**Linux client output**
```
[predator@predator looking_glass]$ [I]               main.c:900  | run                            | Looking Glass ()
[I]               main.c:901  | run                            | Locking Method: Atomic
[I]               main.c:894  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1054 | run                            | Using Clipboard: X11
[I]              spice.c:197  | spice_connect                  | Remote: 127.0.0.1:5900
[I]              spice.c:911  | spice_agent_connect            | Spice agent available, sending start
[I]               main.c:1128 | run                            | Waiting for host to signal it's ready...
[I]              spice.c:995  | spice_agent_process            | clipboard capability detected
[I]              spice.c:409  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]                egl.c:372  | egl_render_startup             | Vendor  : NVIDIA Corporation
[I]                egl.c:373  | egl_render_startup             | Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
[I]                egl.c:374  | egl_render_startup             | Version : OpenGL ES 3.2 NVIDIA 410.93
[I]               main.c:1137 | run                            | Host ready, starting session
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
free(): double free detected in tcache 2
```

**Linux client core dump**
Attached: [core_dump.zip](https://github.com/gnif/LookingGlass/files/2897868/core_dump.zip)
<details><summary>Spoiler: Linux client core dump after attempting text-copy</summary>
<p>

```
           PID: 16499 (looking-glass-c)
           UID: 1000 (predator)
           GID: 1000 (predator)
        Signal: 6 (ABRT)
     Timestamp: Sun 2019-02-24 12:56:52 CET (4min 1s ago)
  Command Line: /home/predator/looking_glass/looking-glass-client-c7666b3
    Executable: /home/predator/looking_glass/looking-glass-client-c7666b3
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (predator)
       Boot ID: a29b6cab46c64e3582cdb6440814249a
    Machine ID: b10968ed8e1641059da56cacf9c9b77d
      Hostname: predator
       Storage: /var/lib/systemd/coredump/core.looking-glass-c.1000.a29b6cab46c64e3582cdb6440814249a.16499.1551009412000000.lz4
       Message: Process 16499 (looking-glass-c) of user 1000 dumped core.
                
                Stack trace of thread 16509:
                #0  0x00007f63d1e7453f raise (libc.so.6)
                #1  0x00007f63d1e5e895 abort (libc.so.6)
                #2  0x00007f63d1eb7927 __libc_message (libc.so.6)
                #3  0x00007f63d1ebe25c malloc_printerr (libc.so.6)
                #4  0x00007f63d1ebfd45 _int_free (libc.so.6)
                #5  0x000000000040b198 n/a (/home/predator/looking_glass/looking-glass-client-c7666b3)
```

</p>
</details>
<br><br>

**Looking glass host on windows guest**
```
[I]          Service.cpp:125  | Service::InitPointers          | Total Available :  32 MB
[I]          Service.cpp:126  | Service::InitPointers          | Max Cursor Size :   1 MB
[I]          Service.cpp:127  | Service::InitPointers          | Max Frame Size  :  15 MB
[I]          Service.cpp:128  | Service::InitPointers          | Cursor          : 000001801FF90080 (0x00000080)
[I]          Service.cpp:134  | Service::InitPointers          | Frame 0         : 0000018020090080 (0x00100080)
[I]          Service.cpp:134  | Service::InitPointers          | Frame 1         : 0000018021010000 (0x01080000)
[I]     CaptureFactory.h:83   | CaptureFactory::DetectDevice   | Trying DXGI
[I]             DXGI.cpp:223  | Capture::DXGI::Initialize      | Device Descripion: NVIDIA GeForce GTX 1080
[I]             DXGI.cpp:224  | Capture::DXGI::Initialize      | Device Vendor ID : 0x10de
[I]             DXGI.cpp:225  | Capture::DXGI::Initialize      | Device Device ID : 0x1b80
[I]             DXGI.cpp:226  | Capture::DXGI::Initialize      | Device Video Mem : 8079 MB
[I]             DXGI.cpp:227  | Capture::DXGI::Initialize      | Device Sys Mem   : 0 MB
[I]             DXGI.cpp:228  | Capture::DXGI::Initialize      | Shared Sys Mem   : 8191 MB
[I]             DXGI.cpp:232  | Capture::DXGI::Initialize      | Capture Size     : 1920 x 1052
[I]             DXGI.cpp:289  | Capture::DXGI::Initialize      | Feature Level    : 0xc100
[I]             DXGI.cpp:359  | Capture::DXGI::Initialize      | Source Format    : DXGI_FORMAT_B8G8R8A8_UNORM
[I]     CaptureFactory.h:86   | CaptureFactory::DetectDevice   | Using DXGI
[I]             DXGI.cpp:658  | Capture::DXGI::Capture         | Pixel Format     : DXGI_FORMAT_B8G8R8A8_UNORMAT_B8G8R8A8_UNORM
```

**Steps taken:**

1. Downloaded and installed looking-glass-host.exe on guest from appveyor (Version c7666b31)
2. Downloaded and installed spice guest agent tools on guest [latest, 2018-01-04 07:49](https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe)
3. Downloaded, compiled and used looking glass version c7666b314bde2622328b5ddd7f16c7493c552d01 on linux

4. Libvirt xml entry was already present
```
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
```
5. Start virtual machine and looking glass _without any arguments_

<br>
<br>

**Observed behavior**
1. Video output works, moving the mouse over the looking glass window hides the mouse on the host, and does not show the mouse of the guest, effectively showing no cursor.
2. Mouse clicks do not reach the guest, keyboard strokes are passed through normally in all cases.
3. When enabling capture mode, mouse functionality is restored and becomes visible again.
4. When using evdev, the mouse on the guest becomes visible and works properly.
5. When copying text in the windows guest using either evdev or capture mode, the looking-glass-client on linux crashes and creates a coredump (Attached, see above)

<br>

**Edit:** Included looking glass host output.<br>Note: the looking glass host does not crash. Also worth mentioning is that the looking glass client does not _always_ crash, I actually managed to copy the looking glass host output by restarting the looking glass client and copying it.

**NB:**
I know this is not a supported version, but figured it might contain useful information for you. I tried to make this issue as comprehensive as possible and hope it contains any useful information.

Thank you so much for your time and efforts you have put into looking glass! I use it daily and I can never go without it again.

**Comment by gnif** [comment]
Thanks, out of curiosity what did you copy from?

**Comment by TerminatorNL** [comment]
Windows explorer file names

**Comment by gnif** [comment]
Can you please elaborate on the exact steps you took?
Also it would be extremely helpful if you could run the client under GDB and provide a back trace when it crashes.

**Comment by TerminatorNL** [comment]
I would love to help, but I have never ran a program using GDB before. I am not entirely sure what I should be doing, I may be doing something entirely wrong.

Furthermore, my steps to make the client crash every time is copy some text, and then open nautilus. It's probably related to focus loss. not sure.

I included a video. I have a multi monitor setup, which explains the clutter at the top left corner.

[Screencast from 02-24-2019 06:25:27 PM.zip](https://github.com/gnif/LookingGlass/files/2898162/Screencast.from.02-24-2019.06.25.27.PM.zip)



GDB says it's missing some debuginfo, I am not entirely sure why.

```
[root@predator predator]# dnf debuginfo-install libdrm-2.4.96-2.fc29.x86_64 mesa-libEGL-18.2.8-1.fc29.x86_64 mesa-libgbm-18.2.8-1.fc29.x86_64 mesa-libglapi-18.2.8-1.fc29.x86_64 systemd-libs-239-9.gite339eae.fc29.x86_64
enabling fedora-cisco-openh264-debuginfo repository
enabling fedora-modular-debuginfo repository
enabling updates-modular-debuginfo repository
enabling updates-debuginfo repository
enabling fedora-debuginfo repository
enabling pgdg10-debuginfo repository
enabling rpmfusion-free-updates-debuginfo repository
enabling rpmfusion-free-debuginfo repository
enabling rpmfusion-nonfree-nvidia-driver-debuginfo repository
Last metadata expiration check: 0:01:35 ago on Sun 24 Feb 2019 06:17:51 PM CET.
Package libdrm-debuginfo-2.4.97-1.fc29.x86_64 is already installed.
Package mesa-libEGL-debuginfo-18.3.4-1.fc29.x86_64 is already installed.
Package mesa-libgbm-debuginfo-18.3.4-1.fc29.x86_64 is already installed.
Package mesa-libglapi-debuginfo-18.3.4-1.fc29.x86_64 is already installed.
Package systemd-libs-debuginfo-239-12.git8bca462.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

```
[predator@predator looking_glass]$ gdb
GNU gdb (GDB) Fedora 8.2-6.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file looking-glass-client-c7666b3 
Reading symbols from looking-glass-client-c7666b3...done.
(gdb) r
Starting program: /home/predator/looking_glass/looking-glass-client-c7666b3 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-26.fc29.x86_64
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]               main.c:900  | run                            | Looking Glass ()
[I]               main.c:901  | run                            | Locking Method: Atomic
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
Missing separate debuginfo for /lib64/libmount.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f8/327d6d1741a9ca39a96f2bc253d74d6f05034e.debug
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]               main.c:894  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1054 | run                            | Using Clipboard: X11
[New Thread 0x7fffe4ec7700 (LWP 30517)]
[I]              spice.c:197  | spice_connect                  | Remote: 127.0.0.1:5900
[I]              spice.c:911  | spice_agent_connect            | Spice agent available, sending start
warning: Loadable section ".note.gnu.property" outside of ELF segments
[New Thread 0x7fffdba99700 (LWP 30518)]
[I]               main.c:1128 | run                            | Waiting for host to signal it's ready...
[I]              spice.c:409  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]              spice.c:995  | spice_agent_process            | clipboard capability detected
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]                egl.c:372  | egl_render_startup             | Vendor  : NVIDIA Corporation
[I]                egl.c:373  | egl_render_startup             | Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
[I]                egl.c:374  | egl_render_startup             | Version : OpenGL ES 3.2 NVIDIA 410.93
[I]               main.c:1137 | run                            | Host ready, starting session
[New Thread 0x7fffd9476700 (LWP 30528)]
[New Thread 0x7fffd8c75700 (LWP 30529)]
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
free(): double free detected in tcache 2

Thread 3 "spiceThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdba99700 (LWP 30518)]
0x00007ffff76ad53f in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libdrm-2.4.96-2.fc29.x86_64 mesa-libEGL-18.2.8-1.fc29.x86_64 mesa-libgbm-18.2.8-1.fc29.x86_64 mesa-libglapi-18.2.8-1.fc29.x86_64 systemd-libs-239-9.gite339eae.fc29.x86_64
(gdb)
```

**Comment by gnif** [comment]
great so far, to get a backtrace when it crashes in gdb type `backtrace` or `bt` and provide the result, this will give me detail on exactly where the crash occurred.

**Comment by TerminatorNL** [comment]
All right, here it is:

```(gdb) backtrace
#0  0x00007ffff76ad53f in raise () from /lib64/libc.so.6
#1  0x00007ffff7697895 in abort () from /lib64/libc.so.6
#2  0x00007ffff76f0927 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff76f725c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff76f8d45 in _int_free () from /lib64/libc.so.6
#5  0x000000000040b198 in spice_agent_on_clipboard ()
    at /home/predator/looking_glass/LookingGlass-c7666b3-clipboard/client/spice/spice.c:1131
#6  0x000000000040cfd6 in spice_agent_process (dataSize=<optimized out>)
    at /home/predator/looking_glass/LookingGlass-c7666b3-clipboard/client/spice/spice.c:1073
#7  0x000000000040d9d5 in spice_on_main_channel_read ()
    at /home/predator/looking_glass/LookingGlass-c7666b3-clipboard/client/spice/spice.c:601
#8  0x000000000040dda1 in spice_process () at /home/predator/looking_glass/LookingGlass-c7666b3-clipboard/client/spice/spice.c:262
#9  0x0000000000407f40 in spiceThread (arg=arg@entry=0x0) at /home/predator/looking_glass/LookingGlass-c7666b3-clipboard/client/main.c:470
#10 0x00007ffff7eb3760 in SDL_RunThread (data=0x576420) at /usr/src/debug/SDL2-2.0.9-1.fc29.x86_64/src/thread/SDL_thread.c:283
#11 0x00007ffff7f2b0fd in RunThread (data=<optimized out>) at /usr/src/debug/SDL2-2.0.9-1.fc29.x86_64/src/thread/pthread/SDL_systhread.c:78
#12 0x00007ffff765358e in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff77726a3 in clone () from /lib64/libc.so.6
```

**Comment by gnif** [comment]
Can you please try the latest commit?

**Comment by TerminatorNL** [comment]
All right, give me a minute.

**Comment by TerminatorNL** [comment]
It managed to crash. It may also be worth mentioning that the cursor also not visible, not sure if it's related to the crash in any way though!

Here's the backtrace: 
```
[predator@predator looking_glass]$ gdb
GNU gdb (GDB) Fedora 8.2-6.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file looking-glass-client-8d48dd97 
Reading symbols from looking-glass-client-8d48dd97...done.
(gdb) r
Starting program: /home/predator/looking_glass/looking-glass-client-8d48dd97 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-26.fc29.x86_64
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]               main.c:900  | run                            | Looking Glass ()
[I]               main.c:901  | run                            | Locking Method: Atomic
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
Missing separate debuginfo for /lib64/libmount.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f8/327d6d1741a9ca39a96f2bc253d74d6f05034e.debug
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]               main.c:894  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1054 | run                            | Using Clipboard: X11
[New Thread 0x7fffe4ec7700 (LWP 11333)]
[I]              spice.c:198  | spice_connect                  | Remote: 127.0.0.1:5900
[I]              spice.c:919  | spice_agent_connect            | Spice agent available, sending start
[New Thread 0x7fffdba99700 (LWP 11334)]
[I]               main.c:1128 | run                            | Waiting for host to signal it's ready...
[I]              spice.c:415  | spice_on_common_read           | notify message: keyboard channel is insecure
[I]              spice.c:1006 | spice_agent_process            | clipboard capability detected
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[I]                egl.c:372  | egl_render_startup             | Vendor  : NVIDIA Corporation
[I]                egl.c:373  | egl_render_startup             | Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
[I]                egl.c:374  | egl_render_startup             | Version : OpenGL ES 3.2 NVIDIA 410.93
[I]               main.c:1137 | run                            | Host ready, starting session
[New Thread 0x7fffd9476700 (LWP 11335)]
[New Thread 0x7fffd8c75700 (LWP 11336)]
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
[I]                x11.c:201  | x11_cb_wmevent                 | Unable to copy "UTF8_STRING" to "text/plain;charset=utf-8" type
free(): double free detected in tcache 2

Thread 3 "spiceThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdba99700 (LWP 11334)]
0x00007ffff76ad53f in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libdrm-2.4.96-2.fc29.x86_64 mesa-libEGL-18.2.8-1.fc29.x86_64 mesa-libgbm-18.2.8-1.fc29.x86_64 mesa-libglapi-18.2.8-1.fc29.x86_64 systemd-libs-239-9.gite339eae.fc29.x86_64
(gdb) bt
#0  0x00007ffff76ad53f in raise () from /lib64/libc.so.6
#1  0x00007ffff7697895 in abort () from /lib64/libc.so.6
#2  0x00007ffff76f0927 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff76f725c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff76f8d45 in _int_free () from /lib64/libc.so.6
#5  0x000000000040b1d8 in spice_agent_on_clipboard () at /home/predator/looking_glass/LookingGlass-8d48dd97/client/spice/spice.c:1146
#6  0x000000000040d02a in spice_agent_process (dataSize=<optimized out>)
    at /home/predator/looking_glass/LookingGlass-8d48dd97/client/spice/spice.c:1087
#7  0x000000000040d9e5 in spice_on_main_channel_read () at /home/predator/looking_glass/LookingGlass-8d48dd97/client/spice/spice.c:609
#8  0x000000000040e181 in spice_process () at /home/predator/looking_glass/LookingGlass-8d48dd97/client/spice/spice.c:268
#9  0x0000000000407f40 in spiceThread (arg=arg@entry=0x0) at /home/predator/looking_glass/LookingGlass-8d48dd97/client/main.c:470
#10 0x00007ffff7eb3760 in SDL_RunThread (data=0x580df0) at /usr/src/debug/SDL2-2.0.9-1.fc29.x86_64/src/thread/SDL_thread.c:283
#11 0x00007ffff7f2b0fd in RunThread (data=<optimized out>)
    at /usr/src/debug/SDL2-2.0.9-1.fc29.x86_64/src/thread/pthread/SDL_systhread.c:78
#12 0x00007ffff765358e in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff77726a3 in clone () from /lib64/libc.so.6
```

**Comment by gnif** [comment]
Thank you for the detailed information. Just FYI master builds are not supported unless you're willing to do the leg work you have done here, it really is appreciated.

I have managed to replicate the fault and identify the problem. I am implementing a solution which should be available soon.

**Comment by TerminatorNL** [comment]
Understood! Thank you very much for all your efforts, you can close this issue since this is a non-master build if you wish :+1:

**Comment by gnif** [comment]
No, this issue is perfect, it is a good example. Once I correct the issue it will be auto closed when I tag it in the commit that fixes it.

**Comment by TerminatorNL** [comment]
That fixed it!

Informational update below, _not an error_:

It seems like installing the **spice guest agent tools** also re-enabled my driver for the QXL controller.
The cursor issue clearly was an user error created by myself, disabling it again and restarting makes everything work like a charm!

![image](https://user-images.githubusercontent.com/13693773/53304130-4ebdce80-3872-11e9-923d-57678e99cc0f.png)
